# Generated by Django 2.0.7 on 2018-10-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancodequestoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='question2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prova2', to='bancodequestoes.Questao', verbose_name='questão2'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='question3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prova3', to='bancodequestoes.Questao', verbose_name='questão3'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='question4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prova4', to='bancodequestoes.Questao', verbose_name='questão4'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='question5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prova5', to='bancodequestoes.Questao', verbose_name='questão5'),
        ),
    ]
