# Generated by Django 2.0.7 on 2018-10-19 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancodequestoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
                ('question1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova1', to='bancodequestoes.Questao', verbose_name='questão1')),
                ('question2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova2', to='bancodequestoes.Questao', verbose_name='questão2')),
                ('question3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova3', to='bancodequestoes.Questao', verbose_name='questão3')),
                ('question4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova4', to='bancodequestoes.Questao', verbose_name='questão4')),
                ('question5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova5', to='bancodequestoes.Questao', verbose_name='questão5')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
            },
        ),
    ]
