# Generated by Django 2.0.7 on 2018-10-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancodequestoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'questão', 'verbose_name_plural': 'questões'},
        ),
    ]
