# Generated by Django 2.0.7 on 2018-10-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancodequestoes', '0002_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagem'),
        ),
    ]
