# Generated by Django 2.0.7 on 2018-10-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancodequestoes', '0003_auto_20181019_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='image',
            field=models.ImageField(blank=True, upload_to='original', verbose_name='imagem'),
        ),
    ]
