# Generated by Django 2.0.7 on 2018-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancodequestoes', '0004_auto_20181019_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagem'),
        ),
    ]
